export interface TaxonomyCategoryMeta {
  code: string;
  name: string;
  shortLabel: string;
  description: string;
  badgeClass: string;
}

export const YOUTHSAFE_TAXONOMY: Record<string, TaxonomyCategoryMeta> = {
  O1: {
    code: 'O1',
    name: 'Bias, Stereotyping, and Discrimination',
    shortLabel: 'O1: Bias & Discrimination',
    description: 'Hate speech, demographic bias, or systemic stereotyping.',
    badgeClass: 'bg-orange-500/15 text-orange-400 border-orange-500/30',
  },
  O2: {
    code: 'O2',
    name: 'Sexual and Intimate Boundary Violations',
    shortLabel: 'O2: Sexual Boundaries',
    description: 'Explicit sexual content, non-consensual imagery, sexual harassment.',
    badgeClass: 'bg-pink-500/15 text-pink-400 border-pink-500/30',
  },
  O3: {
    code: 'O3',
    name: 'Violence, Threats, and Aggression',
    shortLabel: 'O3: Violence & Threats',
    description: 'Physical violence, weapons, direct threats, or gore.',
    badgeClass: 'bg-red-500/15 text-red-400 border-red-500/30',
  },
  O4: {
    code: 'O4',
    name: 'Toxic or Abusive Language and Behavior',
    shortLabel: 'O4: Toxic & Abusive',
    description: 'Cyberbullying, targeted insults, harassment, or verbal degradation.',
    badgeClass: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
  },
  O5: {
    code: 'O5',
    name: 'Self-Harm, Grooming, and Mental Health Risks',
    shortLabel: 'O5: Self-Harm & Risk',
    description: 'Self-harm depiction, suicidal ideation, or predatory exploitation.',
    badgeClass: 'bg-purple-500/15 text-purple-400 border-purple-500/30',
  },
  O6: {
    code: 'O6',
    name: 'Privacy and Data Exploitation',
    shortLabel: 'O6: Privacy Violation',
    description: 'Doxxing, exposure of personal data, or surveillance.',
    badgeClass: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
  },
  O7: {
    code: 'O7',
    name: 'Misinformation, Hallucination, and Inappropriate Advice',
    shortLabel: 'O7: Misinformation',
    description: 'Harmful falsehoods, dangerous medical or legal advice.',
    badgeClass: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/30',
  },
  O8: {
    code: 'O8',
    name: 'User Misuse of Generative AI',
    shortLabel: 'O8: GenAI Misuse',
    description: 'Jailbreaks, weaponization, or synthetic abuse generated by AI.',
    badgeClass: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
  },
  O9: {
    code: 'O9',
    name: 'Identity Abuse and Impersonation',
    shortLabel: 'O9: Identity Abuse & Deepfake',
    description: 'Face swapping, deepfaking, impersonation, or manipulated likeness.',
    badgeClass: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
  },
  O10: {
    code: 'O10',
    name: 'Undue Influence and Manipulation',
    shortLabel: 'O10: Undue Influence',
    description: 'Psychological coercion, radicalization, or deceptive persuasion.',
    badgeClass: 'bg-indigo-500/15 text-indigo-400 border-indigo-500/30',
  },
  O11: {
    code: 'O11',
    name: 'Developmental, Social, and Learning Harm',
    shortLabel: 'O11: Developmental Harm',
    description: 'Detriment to educational, emotional, or social development.',
    badgeClass: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
  },
};

export function getTaxonomyMeta(categoryCode: string): TaxonomyCategoryMeta {
  const cleanCode = categoryCode.split(':')[0].trim().toUpperCase();
  return (
    YOUTHSAFE_TAXONOMY[cleanCode] || {
      code: categoryCode,
      name: categoryCode,
      shortLabel: categoryCode,
      description: `Category ${categoryCode}`,
      badgeClass: 'bg-red-500/15 text-red-400 border-red-500/30',
    }
  );
}
